### ISSUE TITLE
generate JSON files along ser files

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/aips2sqlite#20]
The easy way is to make a temporary modification to the Java code to generate the JSON file as well as the Serialized file, then we know what to put in there.

for
```
rose_autogenerika.ser.clear
rose_ids.ser.clear
rose_conditions.ser.clear
rose_nota.ser.clear
```

**Comment by zdavatz** [comment]
see zdavatz/cpp2sqlite#89

**Comment by bettar** [comment]
Each file is serialised in source file ShoppingCartRose.java function encryptObjectToFile(). The Java serialisation is done by `byte[] serializedBytes = FileOps.serialize(object);` at that point it would be useful for debugging and documentation purposes to also create a corresponding JSON file

**Comment by b123400** [comment]
@bettar  I submitted the PR, the generated JSON files has the follow type in Java:

- rose_nota.ser.json: `HashMap<String, List<NotaPosition>>`
- rose_conditions.ser.json: `HashMap<String, User>`
- rose_ids.ser.json: `HashMap<String, String>`
- rose_autogenerika.ser.json: `ArrayList<String>`

Ref:
https://github.com/zdavatz/aips2sqlite/blob/master/src/com/maxl/java/shared/NotaPosition.java
https://github.com/zdavatz/aips2sqlite/blob/master/src/com/maxl/java/shared/User.java
