### ISSUE TITLE
Error in parsing Kunden_alle.csv

### ISSUE THREAD

**Issue by bettar** [zdavatz/aips2sqlite#24]
The file Kunden_alle.csv is malformed, resulting in (at least) one record being wrong.

The problem is that one doctor contains a semicolon `;` within the string that represents the doctor name (column M). This would be allowed if the whole name was inside double quotes, but that's not the case. The field separator for the file is the same `;` consequently the parsing becomes corrupted.

You can verify the error for the doctor with GLN 7601000275400.

As a result the output file rose_conditions.ser contains bad data.

**Comment by zdavatz** [comment]
please report them in the report file.
