### ISSUE TITLE
Néo -> Neo

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/aips2sqlite#3]
Leider lässt sich in der Datenbank das _Néo Mercazole_ nicht direkt finden, da es mit Néo geschrieben ist, über den Wirkstoff geht es dann…

**Comment by bettar** [comment]
The clients should do "diacritic insensitive" searches for titles in the DB

**Comment by bettar** [comment]
https://stackoverflow.com/questions/2461522/how-do-i-perform-an-accent-insensitive-compare-e-with-è-é-ê-and-ë-in-sql-ser
