### ISSUE TITLE
Generate Fachinfo & Patinfo in Italian

### ISSUE THREAD

**Issue by phr85** [zdavatz/aips2sqlite#4]
Is there a plan to extract / generate also available data in Italian?
As I see JAVA files are binary data, right?

Bests

Philippe

**Comment by zdavatz** [comment]
Italiensch könnte relativ einfach hinzugefügt werden. Wollen wir mal telefonieren?

**Comment by zdavatz** [comment]
done with: https://github.com/zdavatz/aips2sqlite/pull/62
