### ISSUE TITLE
do not use --nodown Option in production.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/aips2sqlite#5]
The option `--nodown` is only used for testing. In production do **not** use the option `--nodown`. My full path and options are:
`/usr/local/src/jre1.8.0_101/bin/java -jar -Xmx6000m /home/zeno/.software/aips2sqlite/jars/aips2sqlite.jar --owner=Axapharm --plain --xml --lang=de --pinfo`

**Comment by jonaspu** [comment]
Resolved.

Old files were not deleted when generating new files. I.e. when a new patient-/fachinfo is released with a different name, the old file in the output folder remains.

Our solution was to delete the whole output folder before loading again.
